import type { AppData, Tool, User, Review, Booking } from "./types";

const users: User[] = [
  {
    id: "u_marcus",
    name: "Marcus Bell",
    email: "marcus@demo.test",
    avatarColor: "from-emerald-400 to-teal-600",
    location: "Portland, OR",
    bio: "Weekend mechanic with a fully stocked garage. Happy to share.",
    joinedYear: 2022,
  },
  {
    id: "u_sofia",
    name: "Sofia Reyes",
    email: "sofia@demo.test",
    avatarColor: "from-rose-400 to-pink-600",
    location: "Portland, OR",
    bio: "Landscape designer. My shed is overflowing with garden gear.",
    joinedYear: 2021,
  },
  {
    id: "u_dan",
    name: "Dan Okafor",
    email: "dan@demo.test",
    avatarColor: "from-amber-400 to-orange-600",
    location: "Beaverton, OR",
    bio: "Carpenter by trade. Tools should be used, not collect dust.",
    joinedYear: 2020,
  },
  {
    id: "u_lena",
    name: "Lena Park",
    email: "lena@demo.test",
    avatarColor: "from-sky-400 to-indigo-600",
    location: "Lake Oswego, OR",
    bio: "DIY renovator slowly fixing up a 1920s bungalow.",
    joinedYear: 2023,
  },
  {
    id: "u_rosa",
    name: "Rosa Delgado",
    email: "rosa@demo.test",
    avatarColor: "from-orange-400 to-amber-700",
    location: "Gresham, OR",
    bio: "Small excavation contractor. I rent out idle machines between jobs — delivery available.",
    joinedYear: 2019,
  },
  {
    id: "u_demo",
    name: "Demo User",
    email: "arasmussen64@gmail.com",
    avatarColor: "from-violet-400 to-fuchsia-600",
    location: "Portland, OR",
    bio: "This is you — the signed-in demo account.",
    joinedYear: 2024,
  },
];

const tools: Tool[] = [
  {
    id: "t_excavator",
    ownerId: "u_rosa",
    title: "Mini Excavator (3.5 Ton)",
    category: "heavy",
    description:
      "Compact 3.5-ton mini excavator, perfect for digging foundations, trenches, and pulling stumps. Rubber tracks won't tear up the yard. Trailer pickup or local delivery for a fee. Operator orientation included.",
    pricePerDay: 285,
    deposit: 1500,
    location: "Gresham, OR",
    condition: "Good",
    image: "🚜",
    createdAt: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "t_backhoe",
    ownerId: "u_rosa",
    title: "Backhoe Loader",
    category: "heavy",
    description:
      "Full-size backhoe loader — front bucket plus rear digging arm. Handles grading, backfilling, and deep trenching. Must show experience or book the optional operator. Delivery within 25 miles available.",
    pricePerDay: 420,
    deposit: 2500,
    location: "Gresham, OR",
    condition: "Good",
    image: "🚜",
    createdAt: "2026-06-15T10:00:00.000Z",
  },
  {
    id: "t_skidsteer",
    ownerId: "u_rosa",
    title: "Skid Steer Loader",
    category: "heavy",
    description:
      "Versatile skid steer with standard bucket. Quick-attach plate fits forks and augers (rentable separately). Great for moving gravel, dirt, and debris around a site.",
    pricePerDay: 240,
    deposit: 1200,
    location: "Gresham, OR",
    condition: "Like New",
    image: "🏗️",
    createdAt: "2026-06-10T10:00:00.000Z",
  },
  {
    id: "t_trackloader",
    ownerId: "u_dan",
    title: "Compact Track Loader",
    category: "heavy",
    description:
      "Rubber-track compact loader with excellent flotation on soft ground. Enclosed heated cab. Ideal for landscaping grades and material handling in wet conditions.",
    pricePerDay: 310,
    deposit: 1800,
    location: "Beaverton, OR",
    condition: "Good",
    image: "🚜",
    createdAt: "2026-06-05T10:00:00.000Z",
  },
  {
    id: "t_trencher",
    ownerId: "u_rosa",
    title: "Ride-On Trencher",
    category: "heavy",
    description:
      "Ride-on trencher that cuts clean 4-foot-deep trenches fast — irrigation, drainage, and electrical runs. Way easier than a walk-behind for long runs.",
    pricePerDay: 195,
    deposit: 900,
    location: "Gresham, OR",
    condition: "Fair",
    image: "🚜",
    createdAt: "2026-06-02T10:00:00.000Z",
  },
  {
    id: "t_scissorlift",
    ownerId: "u_rosa",
    title: "Towable Scissor Lift (26ft)",
    category: "heavy",
    description:
      "Electric scissor lift reaching 26ft working height. Tows behind a standard hitch. Perfect for high interior work, signage, and warehouse jobs. Indoor-safe (no emissions).",
    pricePerDay: 165,
    deposit: 800,
    location: "Gresham, OR",
    condition: "Like New",
    image: "🏗️",
    createdAt: "2026-05-30T10:00:00.000Z",
  },
  {
    id: "t_jack",
    ownerId: "u_marcus",
    title: "Hydraulic Floor Jack (3 Ton)",
    category: "automotive",
    description:
      "Heavy-duty steel floor jack rated for 3 tons. Great for brake jobs and oil changes. Comes with two jack stands.",
    pricePerDay: 18,
    deposit: 60,
    location: "Portland, OR",
    condition: "Good",
    image: "🔧",
    createdAt: "2025-03-02T10:00:00.000Z",
  },
  {
    id: "t_impact",
    ownerId: "u_marcus",
    title: "Cordless Impact Wrench Kit",
    category: "automotive",
    description:
      "1/2\" cordless impact wrench, 700 ft-lbs. Two batteries + charger in a hard case. Perfect for lug nuts and suspension work.",
    pricePerDay: 22,
    deposit: 80,
    location: "Portland, OR",
    condition: "Like New",
    image: "🔩",
    createdAt: "2025-04-11T10:00:00.000Z",
  },
  {
    id: "t_mower",
    ownerId: "u_sofia",
    title: "Self-Propelled Lawn Mower",
    category: "landscaping",
    description:
      "Honda self-propelled gas mower with bag and mulch options. Recently serviced, sharp blade. Tank filled.",
    pricePerDay: 25,
    deposit: 100,
    location: "Portland, OR",
    condition: "Good",
    image: "🌱",
    createdAt: "2025-02-20T10:00:00.000Z",
  },
  {
    id: "t_aerator",
    ownerId: "u_sofia",
    title: "Gas Lawn Aerator",
    category: "landscaping",
    description:
      "Core aerator for reviving compacted lawns. Heavy but worth it every spring. Trailer-loadable.",
    pricePerDay: 45,
    deposit: 120,
    location: "Portland, OR",
    condition: "Fair",
    image: "🌿",
    createdAt: "2025-05-01T10:00:00.000Z",
  },
  {
    id: "t_hedge",
    ownerId: "u_sofia",
    title: "Electric Hedge Trimmer",
    category: "landscaping",
    description:
      "24\" dual-action electric hedge trimmer. Lightweight, quiet, and corded so no battery worries.",
    pricePerDay: 12,
    deposit: 30,
    location: "Portland, OR",
    condition: "Like New",
    image: "✂️",
    createdAt: "2025-05-15T10:00:00.000Z",
  },
  {
    id: "t_tablesaw",
    ownerId: "u_dan",
    title: "Portable Table Saw",
    category: "power",
    description:
      "10\" jobsite table saw with rolling stand. Accurate fence, fresh blade. Will walk you through safe setup.",
    pricePerDay: 35,
    deposit: 150,
    location: "Beaverton, OR",
    condition: "Good",
    image: "🪚",
    createdAt: "2025-01-18T10:00:00.000Z",
  },
  {
    id: "t_drill",
    ownerId: "u_dan",
    title: "Hammer Drill + Bit Set",
    category: "power",
    description:
      "Corded hammer drill for masonry and concrete. Includes a full masonry bit set and safety glasses.",
    pricePerDay: 14,
    deposit: 40,
    location: "Beaverton, OR",
    condition: "Good",
    image: "🛠️",
    createdAt: "2025-03-22T10:00:00.000Z",
  },
  {
    id: "t_sander",
    ownerId: "u_dan",
    title: "Random Orbital Sander",
    category: "power",
    description:
      "5\" orbital sander with assorted grit discs. Great for furniture refinishing and deck prep.",
    pricePerDay: 10,
    deposit: 25,
    location: "Beaverton, OR",
    condition: "Like New",
    image: "🔆",
    createdAt: "2025-04-02T10:00:00.000Z",
  },
  {
    id: "t_wrenchset",
    ownerId: "u_dan",
    title: "Socket & Wrench Master Set",
    category: "hand",
    description:
      "200-piece metric and SAE socket set in a rolling case. Just about every size you'll need.",
    pricePerDay: 9,
    deposit: 40,
    location: "Beaverton, OR",
    condition: "Good",
    image: "🔨",
    createdAt: "2025-02-10T10:00:00.000Z",
  },
  {
    id: "t_ladder",
    ownerId: "u_lena",
    title: "Aluminum Extension Ladder (24ft)",
    category: "construction",
    description:
      "Lightweight 24ft extension ladder. Reaches a two-story gutter comfortably. Stabilizer bar included.",
    pricePerDay: 16,
    deposit: 50,
    location: "Lake Oswego, OR",
    condition: "Good",
    image: "🪜",
    createdAt: "2025-03-30T10:00:00.000Z",
  },
  {
    id: "t_wheelbarrow",
    ownerId: "u_lena",
    title: "Heavy-Duty Wheelbarrow",
    category: "construction",
    description:
      "6 cu-ft steel wheelbarrow with a never-flat tire. Hauled plenty of gravel and concrete.",
    pricePerDay: 8,
    deposit: 20,
    location: "Lake Oswego, OR",
    condition: "Fair",
    image: "🛒",
    createdAt: "2025-04-20T10:00:00.000Z",
  },
  {
    id: "t_sprayer",
    ownerId: "u_lena",
    title: "Airless Paint Sprayer",
    category: "painting",
    description:
      "Airless sprayer that makes fences and large walls quick work. Includes spare tips. Cleaned after every use.",
    pricePerDay: 30,
    deposit: 90,
    location: "Lake Oswego, OR",
    condition: "Like New",
    image: "🎨",
    createdAt: "2025-05-08T10:00:00.000Z",
  },
  {
    id: "t_pressure",
    ownerId: "u_marcus",
    title: "Electric Pressure Washer (2000 PSI)",
    category: "cleaning",
    description:
      "2000 PSI electric pressure washer. Driveways, siding, patios — it eats through grime. Multiple nozzle tips.",
    pricePerDay: 20,
    deposit: 60,
    location: "Portland, OR",
    condition: "Good",
    image: "🧽",
    createdAt: "2025-04-28T10:00:00.000Z",
  },
  {
    id: "t_auger",
    ownerId: "u_dan",
    title: "Plumbing Drain Auger (50ft)",
    category: "plumbing",
    description:
      "Power drain snake with 50ft of cable. Clears stubborn main-line clogs. Gloves included.",
    pricePerDay: 24,
    deposit: 70,
    location: "Beaverton, OR",
    condition: "Good",
    image: "🚿",
    createdAt: "2025-03-12T10:00:00.000Z",
  },
  {
    id: "t_multimeter",
    ownerId: "u_marcus",
    title: "Digital Multimeter + Clamp",
    category: "electrical",
    description:
      "Pro clamp multimeter for troubleshooting circuits, outlets, and automotive electrical. Leads included.",
    pricePerDay: 7,
    deposit: 20,
    location: "Portland, OR",
    condition: "Like New",
    image: "⚡",
    createdAt: "2025-05-19T10:00:00.000Z",
  },
  {
    id: "t_tent",
    ownerId: "u_sofia",
    title: "6-Person Camping Tent",
    category: "outdoor",
    description:
      "Spacious 6-person dome tent, waterproof, sets up in 10 minutes. Great for a weekend trip.",
    pricePerDay: 19,
    deposit: 40,
    location: "Portland, OR",
    condition: "Good",
    image: "🏕️",
    createdAt: "2025-05-22T10:00:00.000Z",
  },
  {
    id: "t_generator",
    ownerId: "u_lena",
    title: "Portable Inverter Generator",
    category: "outdoor",
    description:
      "Quiet 2200W inverter generator. Powers a campsite or backs up the fridge during outages. Fuel-efficient.",
    pricePerDay: 38,
    deposit: 130,
    location: "Lake Oswego, OR",
    condition: "Like New",
    image: "🔌",
    createdAt: "2025-06-01T10:00:00.000Z",
  },
  {
    id: "t_tiller",
    ownerId: "u_sofia",
    title: "Rear-Tine Garden Tiller",
    category: "landscaping",
    description:
      "Gas rear-tine tiller that turns hard clay into a workable bed. Ideal for starting a new vegetable garden.",
    pricePerDay: 40,
    deposit: 110,
    location: "Portland, OR",
    condition: "Good",
    image: "🚜",
    createdAt: "2025-04-05T10:00:00.000Z",
  },
];

const reviews: Review[] = [
  {
    id: "r_1",
    toolId: "t_jack",
    authorId: "u_lena",
    authorName: "Lena Park",
    rating: 5,
    comment: "Worked perfectly for swapping my brake pads. Marcus even threw in tips.",
    date: "2025-04-15",
  },
  {
    id: "r_2",
    toolId: "t_jack",
    authorId: "u_dan",
    authorName: "Dan Okafor",
    rating: 4,
    comment: "Solid jack. A little greasy but did the job.",
    date: "2025-05-02",
  },
  {
    id: "r_3",
    toolId: "t_mower",
    authorId: "u_lena",
    authorName: "Lena Park",
    rating: 5,
    comment: "Started on the first pull. Lawn looks great.",
    date: "2025-05-20",
  },
  {
    id: "r_4",
    toolId: "t_tablesaw",
    authorId: "u_marcus",
    authorName: "Marcus Bell",
    rating: 5,
    comment: "Dan is a pro — the fence was dialed in and cuts were dead straight.",
    date: "2025-03-01",
  },
  {
    id: "r_5",
    toolId: "t_sprayer",
    authorId: "u_dan",
    authorName: "Dan Okafor",
    rating: 4,
    comment: "Painted my whole fence in an afternoon. Cleanup took a bit.",
    date: "2025-05-25",
  },
  {
    id: "r_6",
    toolId: "t_pressure",
    authorId: "u_sofia",
    authorName: "Sofia Reyes",
    rating: 5,
    comment: "Driveway looks brand new. Will rent again.",
    date: "2025-05-10",
  },
];

const bookings: Booking[] = [
  {
    id: "b_1",
    toolId: "t_tablesaw",
    renterId: "u_demo",
    ownerId: "u_dan",
    startDate: "2026-07-04",
    endDate: "2026-07-06",
    days: 3,
    totalPrice: 105,
    status: "confirmed",
    createdAt: "2026-06-20T12:00:00.000Z",
  },
  {
    id: "b_2",
    toolId: "t_pressure",
    renterId: "u_lena",
    ownerId: "u_marcus",
    startDate: "2026-06-28",
    endDate: "2026-06-29",
    days: 2,
    totalPrice: 40,
    status: "pending",
    createdAt: "2026-06-21T09:30:00.000Z",
  },
];

export function getSeedData(): AppData {
  return {
    users: structuredClone(users),
    tools: structuredClone(tools),
    reviews: structuredClone(reviews),
    bookings: structuredClone(bookings),
  };
}

export const DEMO_USER_ID = "u_demo";
